name: cryptical.vim CI Suite
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: nvim -c "Vader! test/*.vader"
        uses: PsychoLlama/vader-action@v1
        with:
          neovim: true
          test-pattern: 'test/*.vader'
